export default [
  {
      userID: "ADM12345",
      name: "John Doe",
      email: "johndoe@example.com",
      phone: "9876543210",
      status: "Active",
      date: "Mon Feb 17 2021 09:30:15 GMT-0300 (Brasilia Standard Time)",
      job: "Software Engineer",
      Role: "Admin",
      department: "IT",
      college: "Computer Science",
      permissions: {
          userManagement: ["View", "Update"],
          roleManagement: ["Create", "Delete"],
          collegeManagement: ["View", "Update", "Delete"],
          accountTypeManagement: ["Create"],
          commission: ["Update", "View"],
          ringtoneManagement: [],
          referManagement: ["Create", "View"],
          tradingRuleManagement: ["Delete"],
          faqManagement: ["Update", "View"],
          loginTracking: ["View"],
          ipTracking: ["View", "Update"],
          userProblemStatistics: ["View"],
          termsAndConditions: ["Update", "View"],
          privacyPolicy: ["Update"],
          settings: ["Create", "Update", "Delete", "View"],
      },
  },
  {
      userID: "ADM12346",
      name: "Jane Smith",
      email: "janesmith@example.com",
      phone: "9876543211",
      status: "Inactive",
      date: "Tue Mar 22 2021 11:15:10 GMT-0300 (Brasilia Standard Time)",
      job: "Project Manager",
      Role: "Admin",
      department: "Operations",
      college: "Business Management",
      permissions: {
          userManagement: ["View"],
          roleManagement: ["Create"],
          collegeManagement: ["View"],
          accountTypeManagement: ["Create"],
          commission: ["View"],
          ringtoneManagement: ["Delete"],
          referManagement: ["Create", "View"],
          tradingRuleManagement: [],
          faqManagement: ["View"],
          loginTracking: ["View"],
          ipTracking: ["Update"],
          userProblemStatistics: ["View"],
          termsAndConditions: [],
          privacyPolicy: ["Update"],
          settings: ["View"],
      },
  },
  {
      userID: "ADM12347",
      name: "Emily Johnson",
      email: "emilyj@example.com",
      phone: "9876543212",
      status: "Active",
      date: "Thu Apr 01 2021 14:45:22 GMT-0300 (Brasilia Standard Time)",
      job: "HR Manager",
      Role: "Super Admin",
      department: "Human Resources",
      college: "Psychology",
      permissions: {
          userManagement: ["Create", "Update", "View", "Delete"],
          roleManagement: ["Create", "Update"],
          collegeManagement: ["View"],
          accountTypeManagement: ["Create"],
          commission: ["View"],
          ringtoneManagement: ["Update"],
          referManagement: ["View"],
          tradingRuleManagement: ["Delete"],
          faqManagement: ["Update"],
          loginTracking: ["View"],
          ipTracking: ["Update"],
          userProblemStatistics: ["View"],
          termsAndConditions: ["Update"],
          privacyPolicy: ["Update"],
          settings: ["Create", "Update", "Delete", "View"],
      },
  },
  {
      userID: "ADM12348",
      name: "Michael Brown",
      email: "michaelb@example.com",
      phone: "9876543213",
      status: "Suspended",
      date: "Fri May 14 2021 10:30:45 GMT-0300 (Brasilia Standard Time)",
      job: "IT Support",
      Role: "Admin",
      department: "IT",
      college: "Information Technology",
      permissions: {
          userManagement: ["View"],
          roleManagement: ["Create"],
          collegeManagement: ["Update"],
          accountTypeManagement: ["Delete"],
          commission: ["Update"],
          ringtoneManagement: ["Create"],
          referManagement: ["View"],
          tradingRuleManagement: ["Delete"],
          faqManagement: [],
          loginTracking: ["View"],
          ipTracking: [],
          userProblemStatistics: ["Update"],
          termsAndConditions: ["View"],
          privacyPolicy: ["Update"],
          settings: ["View"],
      },
  },
  {
      userID: "ADM12349",
      name: "Sarah Davis",
      email: "sarahd@example.com",
      phone: "9876543214",
      status: "Active",
      date: "Wed Jun 23 2021 08:15:30 GMT-0300 (Brasilia Standard Time)",
      job: "Finance Manager",
      Role: "Admin",
      department: "Finance",
      college: "Accounting",
      permissions: {
          userManagement: ["View"],
          roleManagement: [],
          collegeManagement: ["Update", "Delete"],
          accountTypeManagement: ["Create"],
          commission: ["Update"],
          ringtoneManagement: [],
          referManagement: ["View"],
          tradingRuleManagement: ["Delete"],
          faqManagement: ["Update"],
          loginTracking: ["View"],
          ipTracking: ["Update"],
          userProblemStatistics: [],
          termsAndConditions: ["View"],
          privacyPolicy: ["Update"],
          settings: ["View"],
      },
  },
];

// Generate 20 more similar objects
// for (let i = 50; i <= 70; i++) {
//   dummyAdminDataList.push({
//       userID: `ADM12${i}`,
//       name: `User ${i}`,
//       email: `user${i}@example.com`,
//       phone: `98765432${i}`,
//       status: i % 3 === 0 ? "Inactive" : i % 5 === 0 ? "Suspended" : "Active",
//       date: `Thu Jul ${i % 30 + 1} 2021 10:${i % 60}:15 GMT-0300 (Brasilia Standard Time)`,
//       job: "Admin",
//       Role: "Admin",
//       department: "IT",
//       college: "Computer Science",
//       permissions: {
//           userManagement: ["View", "Update"],
//           roleManagement: i % 4 === 0 ? ["Create"] : ["Delete"],
//           collegeManagement: i % 2 === 0 ? ["View", "Update"] : [],
//           accountTypeManagement: ["Create"],
//           commission: ["Update", "View"],
//           ringtoneManagement: [],
//           referManagement: ["Create", "View"],
//           tradingRuleManagement: i % 5 === 0 ? ["Delete"] : [],
//           faqManagement: ["Update", "View"],
//           loginTracking: ["View"],
//           ipTracking: ["View", "Update"],
//           userProblemStatistics: ["View"],
//           termsAndConditions: ["Update", "View"],
//           privacyPolicy: ["Update"],
//           settings: ["Create", "Update", "Delete", "View"],
//       },
//   });
// }
