import img1 from "../../../../assets/img/nfts/Nft1.png"
import img2 from "../../../../assets/img/nfts/Nft2.png"
import img3 from "../../../../assets/img/nfts/Nft3.png"
import img4 from "../../../../assets/img/nfts/Nft4.png"
import img5 from "../../../../assets/img/nfts/Nft5.png"
import img6 from "../../../../assets/img/nfts/Nft6.png"
import img7 from "../../../../assets/img/nfts/NftBanner1.png"
// import img1 from "../../../../assets/img/nfts"
export default [
  {
    ID: 14,
    Title: "The Ultimate Guide to Cooking Pasta",
    Date: "2025-01-05",
    Thumbnail: img7,
    Description: "Learn how to cook pasta perfectly every time.",
    Duration: "15:30",
    Status: "Active",
  },
  {
    ID: 15,
    Title: "10 Minute Morning Yoga Routine",
    Date: "2025-01-10",
    Thumbnail: img5,
    Description: "Start your day with this quick and energizing yoga sequence.",
    Duration: "10:00",
    Status: "Inactive",
  },
  {
    ID: 16,
    Title: "Top 10 Travel Destinations for 2025",
    Date: "2025-01-15",
    Thumbnail: img6,
    Description: "Explore the must-visit places around the world this year.",
    Duration: "12:45",
    Status: "Active",
  },
  {
    ID: 17,
    Title: "How to Master Public Speaking",
    Date: "2025-01-20",
    Thumbnail: img1,
    Description: "Tips and tricks to become a confident public speaker.",
    Duration: "18:20",
    Status: "Inactive",
  },
  {
    ID: 18,
    Title: "The History of Artificial Intelligence",
    Date: "2025-01-25",
    Thumbnail: img1,
    Description: "A comprehensive overview of AI development over the years.",
    Duration: "20:00",
    Status: "Active",
  },
  {
    ID: 19,
    Title: "5 Easy Vegan Recipes for Beginners",
    Date: "2025-01-30",
    Thumbnail: img2,
    Description: "Delicious and simple plant-based meals anyone can make.",
    Duration: "14:10",
    Status: "Inactive",
  },
  {
    ID: 20,
    Title: "Understanding Quantum Computing",
    Date: "2025-02-04",
    Thumbnail: img3,
    Description: "An introduction to the world of quantum computers.",
    Duration: "16:50",
    Status: "Active",
  },
  {
    ID: 21,
    Title: "Beginner's Guide to Meditation",
    Date: "2025-02-09",
    Thumbnail: img4,
    Description: "Learn how to meditate and its benefits for mental health.",
    Duration: "11:30",
    Status: "Inactive",
  },
  {
    ID: 22,
    Title: "Top 5 Programming Languages to Learn in 2025",
    Date: "2025-02-14",
    Thumbnail: img5,
    Description: "Stay ahead in tech with these in-demand programming languages.",
    Duration: "13:25",
    Status: "Inactive",
  },
  {
    ID: 23,
    Title: "How to Build a Personal Brand Online",
    Date: "2025-02-19",
    Thumbnail: img6,
    Description: "Strategies to establish and grow your online presence.",
    Duration: "17:40",
    Status: "Active",
  },
  {
    ID: 24,
    Title: "The Science Behind Intermittent Fasting",
    Date: "2025-02-24",
    Thumbnail: img7,
    Description: "Explore the health benefits and risks of intermittent fasting.",
    Duration: "19:15",
    Status: "Active",
  },
  {
    ID: 25,
    Title: "Photography Tips for Beginners",
    Date: "2025-03-01",
    Thumbnail: img1,
    Description: "Improve your photography skills with these simple tips.",
    Duration: "12:00",
    Status: "Active",
  },
  {
    ID: 26,
    Title: "Understanding Cryptocurrency and Blockchain",
    Date: "2025-03-06",
    Thumbnail: img2,
    Description: "A beginner's guide to digital currencies and the technology behind them.",
    Duration: "21:30",
    Status: "Inactive",
  },
  {
    ID: 27,
    Title: "Home Workout Routine Without Equipment",
    Date: "2025-03-11",
    Thumbnail: img7,
    Description: "Stay fit at home with this no-equipment workout plan.",
    Duration: "15:00",
    Status: "Inactive",
  },
  {
    ID: 28,
    Title: "Time Management Techniques for Productivity",
    Date: "2025-03-16",
    Thumbnail: img1,
    Description: "Effective methods to manage your time and increase productivity.",
    Duration: "14:45",
    Status: "Inactive",
  },
  {
    ID: 29,
    Title: "Exploring the Universe: A Journey Through Space",
    Date: "2025-03-21",
    Thumbnail: img2,
    Description: "Take a virtual tour of the cosmos and learn about its wonders.",
    Duration: "22:10",
    Status: "Active",
  },
  {
    ID: 30,
    Title: "Mastering the Art of Negotiation",
    Date: "2025-03-26",
    Thumbnail: img3,
    Description: "Techniques to improve your negotiation skills in various situations.",
    Duration: "16:25",
    Status: "Active",
  },
  {
    ID: 31,
    Title: "The Benefits of Learning a Second Language",
    Date: "2025-03-31",
    Thumbnail: img4,
    Description: "Discover how being bilingual can enhance your life and career.",
    Duration: "13:50",
    Status: "Active",
  },
  {
    ID: 32,
    Title: "How to Start a Successful YouTube Channel",
    Date: "2025-04-05",
    Thumbnail: img5,
    Description: "Step-by-step guide to creating and growing your YouTube presence.",
    Duration: "18:00",
    Status: "Inactive",
  },
  {
    ID: 33,
    Title: "Understanding Climate Change and Its Impact",
    Date: "2025-04-10",
    Thumbnail: img6,
    Description: "An in-depth look at climate change and what we can do about it.",
    Duration: "20:30",
    Status: "Active",
  },
];
