export default [
  {
    ID: 1,
    CollegeName: "Harvard University",
    Platform: "Instagram",
    Followers: 25000,
    Status: "Active",
    DomainName: "harvard.edu",
    CollegeCode: "HU001",
    Code: "SDFG6543",
    Email: "info@harvard.edu",
    Number: "+1 617-495-1000",
    Commission: 1500,
    Usages: 75,
  },
  {
    ID: 2,
    CollegeName: "Stanford University",
    Platform: "Facebook",
    Followers: 30000,
    Status: "Active",
    DomainName: "stanford.edu",
    CollegeCode: "SU002",
    Code: "ABCD1234",
    Email: "contact@stanford.edu",
    Number: "+1 650-723-2300",
    Commission: 1800,
    Usages: 85,
  },
  {
    ID: 3,
    CollegeName: "MIT",
    Platform: "Twitter",
    Followers: 40000,
    Status: "Inactive",
    DomainName: "mit.edu",
    CollegeCode: "MIT003",
    Code: "XYZ5678",
    Email: "info@mit.edu",
    Number: "+1 617-253-1000",
    Commission: 2000,
    Usages: 95,
  },
  {
    ID: 4,
    CollegeName: "Yale University",
    Platform: "LinkedIn",
    Followers: 22000,
    Status: "Active",
    DomainName: "yale.edu",
    CollegeCode: "YU004",
    Code: "LMNO9876",
    Email: "admin@yale.edu",
    Number: "+1 203-432-4771",
    Commission: 1400,
    Usages: 65,
  },
  {
    ID: 5,
    CollegeName: "Princeton University",
    Platform: "Instagram",
    Followers: 28000,
    Status: "Active",
    DomainName: "princeton.edu",
    CollegeCode: "PU005",
    Code: "JKL7654",
    Email: "contact@princeton.edu",
    Number: "+1 609-258-3000",
    Commission: 1700,
    Usages: 80,
  },
  {
    ID: 6,
    CollegeName: "Oxford University",
    Platform: "Facebook",
    Followers: 32000,
    Status: "Active",
    DomainName: "ox.ac.uk",
    CollegeCode: "OU006",
    Code: "EFGH3210",
    Email: "info@ox.ac.uk",
    Number: "+44 1865 270000",
    Commission: 1900,
    Usages: 88,
  },
  {
    ID: 7,
    CollegeName: "Cambridge University",
    Platform: "Twitter",
    Followers: 35000,
    Status: "Inactive",
    DomainName: "cam.ac.uk",
    CollegeCode: "CU007",
    Code: "WXYZ5432",
    Email: "admin@cam.ac.uk",
    Number: "+44 1223 337733",
    Commission: 2100,
    Usages: 99,
  },
  {
    ID: 8,
    CollegeName: "Columbia University",
    Platform: "Instagram",
    Followers: 29000,
    Status: "Active",
    DomainName: "columbia.edu",
    CollegeCode: "CU008",
    Code: "PQRS8765",
    Email: "support@columbia.edu",
    Number: "+1 212-854-1754",
    Commission: 1750,
    Usages: 78,
  },
  {
    ID: 9,
    CollegeName: "University of Chicago",
    Platform: "LinkedIn",
    Followers: 27000,
    Status: "Active",
    DomainName: "uchicago.edu",
    CollegeCode: "UC009",
    Code: "TUVW6543",
    Email: "help@uchicago.edu",
    Number: "+1 773-702-1234",
    Commission: 1650,
    Usages: 70,
  },
  {
    ID: 10,
    CollegeName: "University of California, Berkeley",
    Platform: "Facebook",
    Followers: 31000,
    Status: "Active",
    DomainName: "berkeley.edu",
    CollegeCode: "UCB010",
    Code: "QRST4321",
    Email: "info@berkeley.edu",
    Number: "+1 510-642-6000",
    Commission: 1850,
    Usages: 82,
  },
  {
    ID: 11,
    CollegeName: "University of Pennsylvania",
    Platform: "Twitter",
    Followers: 26000,
    Status: "Inactive",
    DomainName: "upenn.edu",
    CollegeCode: "UP011",
    Code: "MNOP9876",
    Email: "support@upenn.edu",
    Number: "+1 215-898-5000",
    Commission: 1600,
    Usages: 68,
  },
  {
    ID: 12,
    CollegeName: "Duke University",
    Platform: "Instagram",
    Followers: 25500,
    Status: "Active",
    DomainName: "duke.edu",
    CollegeCode: "DU012",
    Code: "GHIJ1234",
    Email: "contact@duke.edu",
    Number: "+1 919-684-8111",
    Commission: 1500,
    Usages: 75,
  },
  {
    ID: 13,
    CollegeName: "Northwestern University",
    Platform: "LinkedIn",
    Followers: 23000,
    Status: "Active",
    DomainName: "northwestern.edu",
    CollegeCode: "NU013",
    Code: "DEFG5678",
    Email: "info@northwestern.edu",
    Number: "+1 847-491-3741",
    Commission: 1450,
    Usages: 63,
  },
  {
    ID: 14,
    CollegeName: "University of Michigan",
    Platform: "Facebook",
    Followers: 29000,
    Status: "Inactive",
    DomainName: "umich.edu",
    CollegeCode: "UM014",
    Code: "QRST8765",
    Email: "support@umich.edu",
    Number: "+1 734-764-1817",
    Commission: 1700,
    Usages: 77,
  },
  {
    ID: 15,
    CollegeName: "University of Toronto",
    Platform: "Instagram",
    Followers: 28000,
    Status: "Active",
    DomainName: "utoronto.ca",
    CollegeCode: "UT015",
    Code: "XYZT6543",
    Email: "help@utoronto.ca",
    Number: "+1 416-978-2011",
    Commission: 1600,
    Usages: 72,
  },

  {
    ID: 16,
    CollegeName: "University of Edinburgh",
    Platform: "Pinterest",
    Followers: 15000,
    Status: "Inactive",
    DomainName: "ed.ac.uk",
    CollegeCode: "UE016",
    Code: "GHJK5432",
    Email: "info@ed.ac.uk",
    Number: "+44 131 650 1000",
    Commission: 1100,
    Usages: 40,
  },
  {
    ID: 17,
    CollegeName: "University of British Columbia",
    Platform: "Snapchat",
    Followers: 23000,
    Status: "Active",
    DomainName: "ubc.ca",
    CollegeCode: "UBC017",
    Code: "ZXCV4321",
    Email: "info@ubc.ca",
    Number: "+1 604-822-2211",
    Commission: 2400,
    Usages: 110,
  },
  {
    ID: 18,
    CollegeName: "University of Queensland",
    Platform: "LinkedIn",
    Followers: 19000,
    Status: "Active",
    DomainName: "uq.edu.au",
    CollegeCode: "UQ018",
    Code: "TYUI3210",
    Email: "info@uq.edu.au",
    Number: "+61 7 3365 1111",
    Commission: 1700,
    Usages: 70,
  },
  {
    ID: 19,
    CollegeName: "University of Hong Kong",
    Platform: "Instagram",
    Followers: 20000,
    Status: "Inactive",
    DomainName: "hku.hk",
    CollegeCode: "HKU019",
    Code: "FDSA7654",
    Email: "info@hku.hk",
    Number: "+852 2859 2111",
    Commission: 1500,
    Usages: 55,
  },
  {
    ID: 20,
    CollegeName: "University of Michigan",
    Platform: "YouTube",
    Followers: 26000,
    Status: "Active",
    DomainName: "umich.edu",
    CollegeCode: "UM020",
    Code: "PLMN5432",
    Email: "info@umich.edu",
    Number: "+1 734-764-1817",
    Commission: 1900,
    Usages: 100,
  },
];
