export default[     
        {
          "ID": 1,
          "name": "Springfield University",
          "Status": "Active",
          "CollegeCode": "COLL5678",
          "CollegeDomain": "spring.edu",
          "Email": "info@springfield.edu",
          "Number": "+1 555-987-6543",
          "ReferralCode": "REF5678",
          "ReferralCount": 120,
          "ReferralRewards": 20000
        },
        {
          "ID": 2,
          "name": "Springfield University",
          "Status": "Active",
          "CollegeCode": "COLL5679",
          "CollegeDomain": "spring.edu",
          "Email": "admissions@springfield.edu",
          "Number": "+1 555-987-6544",
          "ReferralCode": "REF5679",
          "ReferralCount": 150,
          "ReferralRewards": 25000
        },
        {
          "ID": 3,
          "name": "Westfield University",
          "Status": "Active",
          "CollegeCode": "COLL5680",
          "CollegeDomain": "westfield.edu",
          "Email": "info@westfield.edu",
          "Number": "+1 555-987-6545",
          "ReferralCode": "REF5680",
          "ReferralCount": 90,
          "ReferralRewards": 15000
        },
        {
          "ID": 4,
          "name": "Hilltop College",
          "Status": "Inactive",
          "CollegeCode": "COLL5681",
          "CollegeDomain": "hilltop.edu",
          "Email": "contact@hilltop.edu",
          "Number": "+1 555-987-6546",
          "ReferralCode": "REF5681",
          "ReferralCount": 110,
          "ReferralRewards": 18000
        },
        {
          "ID": 5,
          "name": "Riverdale Institute",
          "Status": "Active",
          "CollegeCode": "COLL5682",
          "CollegeDomain": "riverdale.edu",
          "Email": "info@riverdale.edu",
          "Number": "+1 555-987-6547",
          "ReferralCode": "REF5682",
          "ReferralCount": 200,
          "ReferralRewards": 30000
        },
        {
          "ID": 6,
          "name": "Greenwood University",
          "Status": "Active",
          "CollegeCode": "COLL5683",
          "CollegeDomain": "greenwood.edu",
          "Email": "info@greenwood.edu",
          "Number": "+1 555-987-6548",
          "ReferralCode": "REF5683",
          "ReferralCount": 130,
          "ReferralRewards": 22000
        },
        {
          "ID": 7,
          "name": "Pinecrest Academy",
          "Status": "Active",
          "CollegeCode": "COLL5684",
          "CollegeDomain": "pinecrest.edu",
          "Email": "admissions@pinecrest.edu",
          "Number": "+1 555-987-6549",
          "ReferralCode": "REF5684",
          "ReferralCount": 140,
          "ReferralRewards": 24000
        },
        {
          "ID": 8,
          "name": "Eastbrook College",
          "Status": "Active",
          "CollegeCode": "COLL5685",
          "CollegeDomain": "eastbrook.edu",
          "Email": "info@eastbrook.edu",
          "Number": "+1 555-987-6550",
          "ReferralCode": "REF5685",
          "ReferralCount": 160,
          "ReferralRewards": 26000
        },
        {
          "ID": 9,
          "name": "Lakeside University",
          "Status": "Inactive",
          "CollegeCode": "COLL5686",
          "CollegeDomain": "lakeside.edu",
          "Email": "contact@lakeside.edu",
          "Number": "+1 555-987-6551",
          "ReferralCode": "REF5686",
          "ReferralCount": 50,
          "ReferralRewards": 8000
        },
        {
          "ID": 10,
          "name": "Woodland College",
          "Status": "Active",
          "CollegeCode": "COLL5687",
          "CollegeDomain": "woodland.edu",
          "Email": "info@woodland.edu",
          "Number": "+1 555-987-6552",
          "ReferralCode": "REF5687",
          "ReferralCount": 170,
          "ReferralRewards": 27000
        },
        {
          "ID": 11,
          "name": "Brighton University",
          "Status": "Active",
          "CollegeCode": "COLL5688",
          "CollegeDomain": "brighton.edu",
          "Email": "admissions@brighton.edu",
          "Number": "+1 555-987-6553",
          "ReferralCode": "REF5688",
          "ReferralCount": 180,
          "ReferralRewards": 28000
        },
        {
          "ID": 12,
          "name": "Cedarfield University",
          "Status": "Inactive",
          "CollegeCode": "COLL5689",
          "CollegeDomain": "cedarfield.edu",
          "Email": "info@cedarfield.edu",
          "Number": "+1 555-987-6554",
          "ReferralCode": "REF5689",
          "ReferralCount": 95,
          "ReferralRewards": 15000
        },
        {
          "ID": 13,
          "name": "Silver Creek College",
          "Status": "Active",
          "CollegeCode": "COLL5690",
          "CollegeDomain": "silvercreek.edu",
          "Email": "info@silvercreek.edu",
          "Number": "+1 555-987-6555",
          "ReferralCode": "REF5690",
          "ReferralCount": 190,
          "ReferralRewards": 29000
        },
        {
          "ID": 14,
          "name": "Mountainview College",
          "Status": "Active",
          "CollegeCode": "COLL5691",
          "CollegeDomain": "mountainview.edu",
          "Email": "admissions@mountainview.edu",
          "Number": "+1 555-987-6556",
          "ReferralCode": "REF5691",
          "ReferralCount": 210,
          "ReferralRewards": 30000
        },
        {
          "ID": 15,
          "name": "Sunshine Academy",
          "Status": "Inactive",
          "CollegeCode": "COLL5692",
          "CollegeDomain": "sunshine.edu",
          "Email": "contact@sunshine.edu",
          "Number": "+1 555-987-6557",
          "ReferralCode": "REF5692",
          "ReferralCount": 80,
          "ReferralRewards": 12000
        },
        {
          "ID": 16,
          "name": "Bright Stars College",
          "Status": "Active",
          "CollegeCode": "COLL5693",
          "CollegeDomain": "brightstars.edu",
          "Email": "info@brightstars.edu",
          "Number": "+1 555-987-6558",
          "ReferralCode": "REF5693",
          "ReferralCount": 220,
          "ReferralRewards": 32000
        },
        {
          "ID": 17,
          "name": "Northgate University",
          "Status": "Active",
          "CollegeCode": "COLL5694",
          "CollegeDomain": "northgate.edu",
          "Email": "contact@northgate.edu",
          "Number": "+1 555-987-6559",
          "ReferralCode": "REF5694",
          "ReferralCount": 230,
          "ReferralRewards": 33000
        },
        {
          "ID": 18,
          "name": "Riverside College",
          "Status": "Active",
          "CollegeCode": "COLL5695",
          "CollegeDomain": "riverside.edu",
          "Email": "info@riverside.edu",
          "Number": "+1 555-987-6560",
          "ReferralCode": "REF5695",
          "ReferralCount": 240,
          "ReferralRewards": 35000
        },
        {
          "ID": 19,
          "name": "Starlight College",
          "Status": "Inactive",
          "CollegeCode": "COLL5696",
          "CollegeDomain": "starlight.edu",
          "Email": "admissions@starlight.edu",
          "Number": "+1 555-987-6561",
          "ReferralCode": "REF5696",
          "ReferralCount": 50,
          "ReferralRewards": 7000
        },
        {
          "ID": 20,
          "name": "Golden Valley University",
          "Status": "Active",
          "CollegeCode": "COLL5697",
          "CollegeDomain": "goldenvalley.edu",
          "Email": "info@goldenvalley.edu",
          "Number": "+1 555-987-6562",
          "ReferralCode": "REF5697",
          "ReferralCount": 260,
          "ReferralRewards": 36000
        },
        {
          "ID": 21,
          "name": "Silverstone University",
          "Status": "Active",
          "CollegeCode": "COLL5698",
          "CollegeDomain": "silverstone.edu",
          "Email": "contact@silverstone.edu",
          "Number": "+1 555-987-6563",
          "ReferralCode": "REF5698",
          "ReferralCount": 270,
          "ReferralRewards": 37000
        }
      ]
      