export default [
  {
    ID: 1,
    name: "Jane Smith",
    Status: "Active",
    Platform: "Instagram",
    Email: "jane.smith@example.com",
    Number: "+1 555-987-6543",
    ReferralCode: "REF5678",
    ReferralCount: 120,
    ReferralRewards: 20000,
  },
  {
    ID: 2,
    name: "John Doe",
    Status: "Inactive",
    Platform: "Facebook",
    Email: "john.doe@example.com",
    Number: "+1 555-123-4567",
    ReferralCode: "REF1234",
    ReferralCount: 75,
    ReferralRewards: 15000,
  },
  {
    ID: 3,
    name: "Alice Johnson",
    Status: "Active",
    Platform: "Twitter",
    Email: "alice.johnson@example.com",
    Number: "+1 555-234-5678",
    ReferralCode: "REF9012",
    ReferralCount: 90,
    ReferralRewards: 18000,
  },
  {
    ID: 4,
    name: "Robert Brown",
    Status: "Pending",
    Platform: "LinkedIn",
    Email: "robert.brown@example.com",
    Number: "+1 555-345-6789",
    ReferralCode: "REF3456",
    ReferralCount: 50,
    ReferralRewards: 10000,
  },
  {
    ID: 5,
    name: "Emily White",
    Status: "Active",
    Platform: "YouTube",
    Email: "emily.white@example.com",
    Number: "+1 555-456-7890",
    ReferralCode: "REF7890",
    ReferralCount: 200,
    ReferralRewards: 40000,
  },
  {
    ID: 6,
    name: "Michael Davis",
    Status: "Inactive",
    Platform: "Instagram",
    Email: "michael.davis@example.com",
    Number: "+1 555-567-8901",
    ReferralCode: "REF1111",
    ReferralCount: 35,
    ReferralRewards: 7000,
  },
  {
    ID: 7,
    name: "Sophia Wilson",
    Status: "Active",
    Platform: "Facebook",
    Email: "sophia.wilson@example.com",
    Number: "+1 555-678-9012",
    ReferralCode: "REF2222",
    ReferralCount: 130,
    ReferralRewards: 26000,
  },
  {
    ID: 8,
    name: "Daniel Martinez",
    Status: "Pending",
    Platform: "Twitter",
    Email: "daniel.martinez@example.com",
    Number: "+1 555-789-0123",
    ReferralCode: "REF3333",
    ReferralCount: 45,
    ReferralRewards: 9000,
  },
  {
    ID: 9,
    name: "Olivia Garcia",
    Status: "Active",
    Platform: "LinkedIn",
    Email: "olivia.garcia@example.com",
    Number: "+1 555-890-1234",
    ReferralCode: "REF4444",
    ReferralCount: 85,
    ReferralRewards: 17000,
  },
  {
    ID: 10,
    name: "William Taylor",
    Status: "Inactive",
    Platform: "YouTube",
    Email: "william.taylor@example.com",
    Number: "+1 555-901-2345",
    ReferralCode: "REF5555",
    ReferralCount: 20,
    ReferralRewards: 4000,
  },
  {
    ID: 11,
    name: "Ethan Clark",
    Status: "Active",
    Platform: "Instagram",
    Email: "ethan.clark@example.com",
    Number: "+1 555-012-3456",
    ReferralCode: "REF1313",
    ReferralCount: 95,
    ReferralRewards: 19000,
  },
  {
    ID: 12,
    name: "Amelia Lee",
    Status: "Pending",
    Platform: "Facebook",
    Email: "amelia.lee@example.com",
    Number: "+1 555-234-5670",
    ReferralCode: "REF1414",
    ReferralCount: 60,
    ReferralRewards: 12000,
  },
  {
    ID: 13,
    name: "Henry Scott",
    Status: "Active",
    Platform: "Twitter",
    Email: "henry.scott@example.com",
    Number: "+1 555-345-6781",
    ReferralCode: "REF1515",
    ReferralCount: 125,
    ReferralRewards: 25000,
  },
  {
    ID: 14,
    name: "Chloe King",
    Status: "Inactive",
    Platform: "LinkedIn",
    Email: "chloe.king@example.com",
    Number: "+1 555-456-7892",
    ReferralCode: "REF1616",
    ReferralCount: 55,
    ReferralRewards: 11000,
  },
  {
    ID: 15,
    name: "Lucas Young",
    Status: "Active",
    Platform: "YouTube",
    Email: "lucas.young@example.com",
    Number: "+1 555-567-8903",
    ReferralCode: "REF1717",
    ReferralCount: 140,
    ReferralRewards: 28000,
  },
  {
    ID: 16,
    name: "Ella Hall",
    Status: "Pending",
    Platform: "Instagram",
    Email: "ella.hall@example.com",
    Number: "+1 555-678-9014",
    ReferralCode: "REF1818",
    ReferralCount: 75,
    ReferralRewards: 15000,
  },
  {
    ID: 17,
    name: "Mason Allen",
    Status: "Active",
    Platform: "Facebook",
    Email: "mason.allen@example.com",
    Number: "+1 555-789-0125",
    ReferralCode: "REF1919",
    ReferralCount: 160,
    ReferralRewards: 32000,
  },

  {
    ID: 18,
    name: "Liam Carter",
    Status: "Active",
    Platform: "Instagram",
    Email: "liam.carter@example.com",
    Number: "+1 555-890-1236",
    ReferralCode: "REF2020",
    ReferralCount: 180,
    ReferralRewards: 36000,
  },
  {
    ID: 19,
    name: "Charlotte Baker",
    Status: "Inactive",
    Platform: "Facebook",
    Email: "charlotte.baker@example.com",
    Number: "+1 555-901-2347",
    ReferralCode: "REF2121",
    ReferralCount: 40,
    ReferralRewards: 8000,
  },
  {
    ID: 20,
    name: "Jack Hill",
    Status: "Pending",
    Platform: "Twitter",
    Email: "jack.hill@example.com",
    Number: "+1 555-012-3458",
    ReferralCode: "REF2222",
    ReferralCount: 65,
    ReferralRewards: 13000,
  },
  {
    ID: 21,
    name: "Avery Wright",
    Status: "Active",
    Platform: "LinkedIn",
    Email: "avery.wright@example.com",
    Number: "+1 555-123-4569",
    ReferralCode: "REF2323",
    ReferralCount: 110,
    ReferralRewards: 22000,
  },
  {
    ID: 22,
    name: "Evelyn Harris",
    Status: "Inactive",
    Platform: "YouTube",
    Email: "evelyn.harris@example.com",
    Number: "+1 555-234-5670",
    ReferralCode: "REF2424",
    ReferralCount: 30,
    ReferralRewards: 6000,
  },
  {
    ID: 23,
    name: "Logan Nelson",
    Status: "Active",
    Platform: "Instagram",
    Email: "logan.nelson@example.com",
    Number: "+1 555-345-6781",
    ReferralCode: "REF2525",
    ReferralCount: 150,
    ReferralRewards: 30000,
  },
  {
    ID: 24,
    name: "Harper Green",
    Status: "Pending",
    Platform: "Facebook",
    Email: "harper.green@example.com",
    Number: "+1 555-456-7892",
    ReferralCode: "REF2626",
    ReferralCount: 55,
    ReferralRewards: 11000,
  },
  {
    ID: 25,
    name: "Elijah Adams",
    Status: "Active",
    Platform: "Twitter",
    Email: "elijah.adams@example.com",
    Number: "+1 555-567-8903",
    ReferralCode: "REF2727",
    ReferralCount: 135,
    ReferralRewards: 27000,
  },
  {
    ID: 26,
    name: "Scarlett Walker",
    Status: "Inactive",
    Platform: "LinkedIn",
    Email: "scarlett.walker@example.com",
    Number: "+1 555-678-9014",
    ReferralCode: "REF2828",
    ReferralCount: 25,
    ReferralRewards: 5000,
  },
  {
    ID: 27,
    name: "Henry Robinson",
    Status: "Active",
    Platform: "YouTube",
    Email: "henry.robinson@example.com",
    Number: "+1 555-789-0125",
    ReferralCode: "REF2929",
    ReferralCount: 170,
    ReferralRewards: 34000,
  },
  {
    ID: 28,
    name: "Grace Lewis",
    Status: "Pending",
    Platform: "Instagram",
    Email: "grace.lewis@example.com",
    Number: "+1 555-890-1236",
    ReferralCode: "REF3030",
    ReferralCount: 80,
    ReferralRewards: 16000,
  },
  {
    ID: 29,
    name: "Daniel Young",
    Status: "Active",
    Platform: "Facebook",
    Email: "daniel.young@example.com",
    Number: "+1 555-901-2347",
    ReferralCode: "REF3131",
    ReferralCount: 100,
    ReferralRewards: 20000,
  },
  {
    ID: 30,
    name: "Zoe King",
    Status: "Inactive",
    Platform: "Twitter",
    Email: "zoe.king@example.com",
    Number: "+1 555-012-3458",
    ReferralCode: "REF3232",
    ReferralCount: 45,
    ReferralRewards: 9000,
  },
  {
    ID: 31,
    name: "Matthew Scott",
    Status: "Active",
    Platform: "LinkedIn",
    Email: "matthew.scott@example.com",
    Number: "+1 555-123-4569",
    ReferralCode: "REF3333",
    ReferralCount: 125,
    ReferralRewards: 25000,
  },
];
