export default [
  {
    ID: 43,
    Title: "Silent Shore",
    Date: "2024-12-25",
    Description: "A quiet shore with gentle waves lapping at the sand.",
    Duration: "00:50",
    Status: "Active",
  },
  {
    ID: 44,
    Title: "Ocean Whisper",
    Date: "2024-12-24",
    Description: "The soft whisper of the ocean breeze at dusk.",
    Duration: "01:00",
    Status: "Inactive",
  },
  {
    ID: 45,
    Title: "Seaside Escape",
    Date: "2024-12-23",
    Description: "A perfect escape to a peaceful seaside.",
    Duration: "01:10",
    Status: "Active",
  },
  {
    ID: 46,
    Title: "Moonlit Waves",
    Date: "2024-12-22",
    Description: "Waves crashing gently under the moonlight.",
    Duration: "00:55",
    Status: "Inactive",
  },
  {
    ID: 47,
    Title: "Whispering Winds",
    Date: "2024-12-21",
    Description: "Soft winds whispering through the trees and the sea.",
    Duration: "00:45",
    Status: "Active",
  },
  {
    ID: 48,
    Title: "Coral Lagoon",
    Date: "2024-12-20",
    Description: "The tranquil beauty of a coral reef lagoon.",
    Duration: "01:00",
    Status: "Inactive",
  },
  {
    ID: 49,
    Title: "Tropical Oasis",
    Date: "2024-12-19",
    Description: "A tropical oasis with vibrant flora and fauna.",
    Duration: "01:15",
    Status: "Active",
  },
  {
    ID: 50,
    Title: "Palm Grove",
    Date: "2024-12-18",
    Description: "A serene grove filled with towering palm trees.",
    Duration: "01:05",
    Status: "Inactive",
  },
  {
    ID: 51,
    Title: "Sunset Serenade",
    Date: "2024-12-17",
    Description: "A serenade as the sun sets over the ocean horizon.",
    Duration: "01:20",
    Status: "Active",
  },
  {
    ID: 52,
    Title: "Tidal Rhythms",
    Date: "2024-12-16",
    Description: "The rhythmic sound of tides moving along the shore.",
    Duration: "00:50",
    Status: "Inactive",
  },
  {
    ID: 53,
    Title: "Island Breeze",
    Date: "2024-12-15",
    Description: "A soothing breeze from a tropical island.",
    Duration: "00:55",
    Status: "Active",
  },
  {
    ID: 54,
    Title: "Crystal Coast",
    Date: "2024-12-14",
    Description: "The sound of waves crashing on a crystal-clear coast.",
    Duration: "01:00",
    Status: "Inactive",
  },
  {
    ID: 55,
    Title: "Tropical Rain",
    Date: "2024-12-13",
    Description: "A gentle tropical rain shower in the jungle.",
    Duration: "01:10",
    Status: "Active",
  },
  {
    ID: 56,
    Title: "Lagoon Dream",
    Date: "2024-12-12",
    Description: "A dreamlike melody inspired by a calm lagoon.",
    Duration: "01:20",
    Status: "Inactive",
  },
  {
    ID: 57,
    Title: "Breezy Shores",
    Date: "2024-12-11",
    Description: "The sound of breezes flowing across the shore.",
    Duration: "00:45",
    Status: "Active",
  },
  {
    ID: 58,
    Title: "Sailboat Journey",
    Date: "2024-12-10",
    Description: "A peaceful sailboat journey across calm waters.",
    Duration: "00:55",
    Status: "Inactive",
  },
  {
    ID: 59,
    Title: "Waves of Serenity",
    Date: "2024-12-09",
    Description: "The serene sound of waves gently rolling in.",
    Duration: "01:00",
    Status: "Active",
  },
  {
    ID: 60,
    Title: "Golden Horizon",
    Date: "2024-12-08",
    Description: "The golden hues of the horizon during sunset.",
    Duration: "01:10",
    Status: "Inactive",
  },
  {
    ID: 61,
    Title: "Island Retreat",
    Date: "2024-12-07",
    Description: "A retreat on a remote tropical island.",
    Duration: "00:50",
    Status: "Active",
  },
  {
    ID: 62,
    Title: "Tropical Melody",
    Date: "2024-12-06",
    Description: "A melody inspired by the rhythm of the tropics.",
    Duration: "01:05",
    Status: "Inactive",
  },
  {
    ID: 63,
    Title: "Ocean Breeze",
    Date: "2024-12-05",
    Description: "A cool ocean breeze sweeping through the air.",
    Duration: "00:45",
    Status: "Active",
  },
  {
    ID: 64,
    Title: "Palm Shadows",
    Date: "2024-12-04",
    Description: "The calming sound of palm trees swaying in the wind.",
    Duration: "01:00",
    Status: "Inactive",
  },
  {
    ID: 65,
    Title: "Sea Breeze Symphony",
    Date: "2024-12-03",
    Description: "The symphony of waves and wind at the seashore.",
    Duration: "01:10",
    Status: "Active",
  },
];
