export default[
  {
    "ID": 1,
    "CollegeName": "Harvard University",
    "platform": "Instagram",
    "followers": 25000,
    "Status": "Active",
    "DomainName": "harvard.edu",
    "CollegeCode": "HU001",
    "Code": "SDFG6543",
    "Email": "info@harvard.edu",
    "Number": "+1 617-495-1000",
    "Commission": 1500,
    "Usages": 75
  },
  {
    "ID": 2,
    "CollegeName": "Stanford University",
    "platform": "Twitter",
    "followers": 18000,
    "Status": "Inactive",
    "DomainName": "stanford.edu",
    "CollegeCode": "SU002",
    "Code": "ASDF1234",
    "Email": "info@stanford.edu",
    "Number": "+1 650-723-2300",
    "Commission": 1200,
    "Usages": 50
  },
  {
    "ID": 3,
    "CollegeName": "MIT",
    "platform": "YouTube",
    "followers": 30000,
    "Status": "Active",
    "DomainName": "mit.edu",
    "CollegeCode": "MIT003",
    "Code": "ZXCV9876",
    "Email": "info@mit.edu",
    "Number": "+1 617-253-1000",
    "Commission": 2000,
    "Usages": 100
  },
  {
    "ID": 4,
    "CollegeName": "University of California, Berkeley",
    "platform": "TikTok",
    "followers": 15000,
    "Status": "Active",
    "DomainName": "berkeley.edu",
    "CollegeCode": "UCB004",
    "Code": "LKJH5432",
    "Email": "info@berkeley.edu",
    "Number": "+1 510-642-6000",
    "Commission": 1700,
    "Usages": 80
  },
  {
    "ID": 5,
    "CollegeName": "Yale University",
    "platform": "Facebook",
    "followers": 22000,
    "Status": "Active",
    "DomainName": "yale.edu",
    "CollegeCode": "YU005",
    "Code": "QWER4321",
    "Email": "info@yale.edu",
    "Number": "+1 203-432-4771",
    "Commission": 1900,
    "Usages": 90
  },
  {
    "ID": 6,
    "CollegeName": "Princeton University",
    "platform": "Instagram",
    "followers": 20000,
    "Status": "Inactive",
    "DomainName": "princeton.edu",
    "CollegeCode": "PU006",
    "Code": "PLMN1234",
    "Email": "info@princeton.edu",
    "Number": "+1 609-258-3000",
    "Commission": 1500,
    "Usages": 60
  },
  {
    "ID": 7,
    "CollegeName": "University of Chicago",
    "platform": "Pinterest",
    "followers": 17000,
    "Status": "Active",
    "DomainName": "uchicago.edu",
    "CollegeCode": "UC007",
    "Code": "BNVC6543",
    "Email": "info@uchicago.edu",
    "Number": "+1 773-702-1234",
    "Commission": 1300,
    "Usages": 70
  },
  {
    "ID": 8,
    "CollegeName": "Columbia University",
    "platform": "Snapchat",
    "followers": 23000,
    "Status": "Active",
    "DomainName": "columbia.edu",
    "CollegeCode": "CU008",
    "Code": "GHJK9876",
    "Email": "info@columbia.edu",
    "Number": "+1 212-854-1754",
    "Commission": 2100,
    "Usages": 95
  },
  {
    "ID": 9,
    "CollegeName": "University of Oxford",
    "platform": "LinkedIn",
    "followers": 35000,
    "Status": "Active",
    "DomainName": "ox.ac.uk",
    "CollegeCode": "UO009",
    "Code": "TYUI5432",
    "Email": "info@ox.ac.uk",
    "Number": "+44 1865 270000",
    "Commission": 3000,
    "Usages": 120
  },
  {
    "ID": 10,
    "CollegeName": "University of Cambridge",
    "platform": "Instagram",
    "followers": 32000,
    "Status": "Inactive",
    "DomainName": "cam.ac.uk",
    "CollegeCode": "UC010",
    "Code": "FDSA4321",
    "Email": "info@cam.ac.uk",
    "Number": "+44 1223 337733",
    "Commission": 2800,
    "Usages": 110
  },
  {
    "ID": 11,
    "CollegeName": "University of Toronto",
    "platform": "YouTube",
    "followers": 25000,
    "Status": "Active",
    "DomainName": "utoronto.ca",
    "CollegeCode": "UT011",
    "Code": "ZXASQW12",
    "Email": "info@utoronto.ca",
    "Number": "+1 416-978-2011",
    "Commission": 1600,
    "Usages": 85
  },
  {
    "ID": 12,
    "CollegeName": "University of Sydney",
    "platform": "Twitter",
    "followers": 18000,
    "Status": "Active",
    "DomainName": "sydney.edu.au",
    "CollegeCode": "US012",
    "Code": "POIU6543",
    "Email": "info@sydney.edu.au",
    "Number": "+61 2 9351 2222",
    "Commission": 1400,
    "Usages": 75
  },
  {
    "ID": 13,
    "CollegeName": "University of Melbourne",
    "platform": "Instagram",
    "followers": 19000,
    "Status": "Inactive",
    "DomainName": "unimelb.edu.au",
    "CollegeCode": "UM013",
    "Code": "LKJH3214",
    "Email": "info@unimelb.edu.au",
    "Number": "+61 3 9035 5511",
    "Commission": 1300,
    "Usages": 50
  },
  {
    "ID": 14,
    "CollegeName": "National University of Singapore",
    "platform": "TikTok",
    "followers": 22000,
    "Status": "Active",
    "DomainName": "nus.edu.sg",
    "CollegeCode": "NUS014",
    "Code": "BNMV7654",
    "Email": "info@nus.edu.sg",
    "Number": "+65 6516 6666",
    "Commission": 2500,
    "Usages": 100
  },
  {
    "ID": 15,
    "CollegeName": "University of California, Los Angeles",
    "platform": "Facebook",
    "followers": 21000,
    "Status": "Active",
    "DomainName": "ucla.edu",
    "CollegeCode": "UCLA015",
    "Code": "ASDF8765",
    "Email": "info@ucla.edu",
    "Number": "+1 310-825-4321",
    "Commission": 2000,
    "Usages": 90
  },
  {
    "ID": 16,
    "CollegeName": "University of Edinburgh",
    "platform": "Pinterest",
    "followers": 15000,
    "Status": "Inactive",
    "DomainName": "ed.ac.uk",
    "CollegeCode": "UE016",
    "Code": "GHJK5432",
    "Email": "info@ed.ac.uk",
    "Number": "+44 131 650 1000",
    "Commission": 1100,
    "Usages": 40
  },
  {
    "ID": 17,
    "CollegeName": "University of British Columbia",
    "platform": "Snapchat",
    "followers": 23000,
    "Status": "Active",
    "DomainName": "ubc.ca",
    "CollegeCode": "UBC017",
    "Code": "ZXCV4321",
    "Email": "info@ubc.ca",
    "Number": "+1 604-822-2211",
    "Commission": 2400,
    "Usages": 110
  },
  {
    "ID": 18,
    "CollegeName": "University of Queensland",
    "platform": "LinkedIn",
    "followers": 19000,
    "Status": "Active",
    "DomainName": "uq.edu.au",
    "CollegeCode": "UQ018",
    "Code": "TYUI3210",
    "Email": "info@uq.edu.au",
    "Number": "+61 7 3365 1111",
    "Commission": 1700,
    "Usages": 70
  },
  {
    "ID": 19,
    "CollegeName": "University of Hong Kong",
    "platform": "Instagram",
    "followers": 20000,
    "Status": "Inactive",
    "DomainName": "hku.hk",
    "CollegeCode": "HKU019",
    "Code": "FDSA7654",
    "Email": "info@hku.hk",
    "Number": "+852 2859 2111",
    "Commission": 1500,
    "Usages": 55
  },
  {
    "ID": 20,
    "CollegeName": "University of Michigan",
    "platform": "YouTube",
    "followers": 26000,
    "Status": "Active",
    "DomainName": "umich.edu",
    "CollegeCode": "UM020",
    "Code": "PLMN5432",
    "Email": "info@umich.edu",
    "Number": "+1 734-764-1817",
    "Commission": 1900,
    "Usages": 100
  }
]
